apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-counter
spec:
  selector:
    matchLabels:
      app: counter
  replicas: 2
  template:
    metadata:
      labels:
        app: counter
        release: {{.Release.Name}}
    spec:
      containers:
        - name: main
          image: ondrejsika/counter
          resources:
            requests:
              cpu: 20m
              memory: 30Mi
            limits:
              cpu: 50m
              memory: 60Mi
          env:
            - name: REDIS
              value: {{.Release.Name}}-redis
          ports:
            - containerPort: 80
---
